require_relative './builder/pages_compiler'

namespace :server do
  desc "Start the server, bro"
  task :start do
    puts 'Server runs on port: 9080'
    puts '---'
    exec 'cd build && ruby -run -ehttpd . -p 9080'
  end
end

namespace :assets do
  desc "compile some assets"
  task :compile do
    `mkdir -p build/assets`

    #compile_javascript
    Rake::Task["assets:compile_pages"].invoke
  end

  task :compile_pages do
    `cp -R site/pages build/pages`

    Dir.glob('site/pages/*').each do |dir|
      PagesCompiler.compile(pages_in(dir), template: 'site/index.html')
    end
  end

  private

  def compile_javascript
    build_page_list
    `browserify node_modules/app/app.js -o build/assets/app.js`
    `browserify spec/spec_manifest.js -o test_site/compiled_specs.js`
  end

  def build_page_list
    File.open('node_modules/app/pages/cache_machine/page_list.js', 'w') do |f|
      f.puts "// this file was autogenerated by a rake task."
      f.puts "module.exports = ["
      f.puts pages.map {|a| %{'#{a.sub(/\.html$/, '')}'}}.join(",\n")
      f.puts "];"
    end
  end

  private

  def pages_in(dir)
    chunk_dir = File.join(dir, 'chunks', '*.html')
    Dir.glob(chunk_dir)
  end
end
