require_relative './builder/pages_compiler'
require 'json'

namespace :server do
  desc "Start the server, bro"
  task :start do
    puts 'Server runs on port: 9080'
    puts '---'
    exec 'cd build && ruby -run -ehttpd . -p 9080'
  end
end

namespace :assets do
  desc "compile some assets"
  task :compile do
    `mkdir -p build/assets`

    Rake::Task["assets:compile_pages"].invoke
    compile_javascript
  end

  task :compile_pages do
    `cp -R site/pages build/pages`

    pages = []
    Dir.glob('site/pages/*').each do |dir|
      PagesCompiler.compile(pages_in(dir), template: 'site/index.html')

      pages << pages_in(dir).map {|p| Page.new(p) }
    end
    build_page_list(pages.flatten)
  end

  private

  def compile_javascript
    `browserify node_modules/app/app.js -o build/assets/app.js`
    `browserify spec/spec_manifest.js -o test_site/compiled_specs.js`
  end

  def build_page_list(pages)
    File.open('node_modules/app/pages/cache_machine/pages_list.js', 'w') do |f|
      f.puts "// this file was autogenerated by a rake task."
      f.puts "module.exports = ["
      pages.each do |page|
        f.puts "#{JSON.pretty_generate(page.info)},"
      end
      f.puts "];"
    end
  end

  private

  def pages_in(dir)
    chunk_dir = File.join(dir, 'chunks', '*.html')
    Dir.glob(chunk_dir)
  end
end
