require_relative './builder/articles_compiler'

namespace :server do
  desc "Start the server, bro"
  task :start do
    puts 'Server runs on port: 9080'
    puts '---'
    exec 'cd build && ruby -run -ehttpd . -p 9080'
  end
end

namespace :assets do
  desc "compile some assets"
  task :compile do
    `mkdir -p build/assets`

    compile_javascript
     Rake::Task["assets:compile_articles"].invoke
  end

  task :compile_articles do
    `cp -R site/articles build/articles`
    ArticlesCompiler.compile(articles, template: 'site/index.html')
  end

  private

  def compile_javascript
    build_article_list
    `browserify node_modules/app/app.js -o build/assets/app.js`
    `browserify spec/spec_manifest.js -o test_site/compiled_specs.js`
  end

  def build_article_list
    File.open('node_modules/app/articles/cache_machine/article_list.js', 'w') do |f|
      f.puts "// this file was autogenerated by a rake task."
      f.puts "module.exports = ["
      f.puts articles.map {|a| %{'#{a.sub(/\.html$/, '')}'}}.join(",\n")
      f.puts "];"
    end
  end

  private

  def articles

    Dir.chdir('site/articles/chunks') do
      Dir.glob('*.html')
    end
  end
end
