#!/bin/bash -ex

rm -rf deploy
rake assets:compile
cp -R build deploy
./node_modules/uglifyjs/bin/uglifyjs build/assets/app.js > deploy/assets/app.js
sass css/app.scss --style compressed > deploy/assets/app.css
echo "success!"
